-- =============================================================================
-- 0009_grants.sql
-- Historical placeholder.
--
-- The early schema had a standalone grants table. Grant lifecycle data is now
-- modeled canonically as holding-level grant_details in migration 0041.
-- This file intentionally creates no tables so the migration numbering remains
-- stable without leaving two competing grant parents in the active schema.
-- =============================================================================
