-- =============================================================================
-- 0012_owner_tax_profile.sql
-- REMOVED: The legacy personal tax profile table defined here was superseded
-- by the canonical tax data model in 0013_tax_contributions.sql.
--
-- Canonical sources for personal tax data:
--   tax_profiles  — per-portfolio/year planning inputs (filing status, etc.)
--   tax_years     — AGI per portfolio/year (adjusted_gross_income column)
--   tax_contributions  — charitable contribution records
--   tax_carryforwards  — multi-year carryforward tracking
--
-- This file is intentionally empty so the migration runner keeps a
-- contiguous sequence without gaps.
-- Depends on: 0001, 0004
-- =============================================================================
