-- =============================================================================
-- 0020_ai_portfolio_manager.sql
-- Historical placeholder.
--
-- The early schema created ai_conversations, ai_messages, and ai_action_log.
-- Active AI state is modeled canonically by ai_sessions and ai_actions in
-- migration 0033. This file intentionally creates no tables so the migration
-- numbering remains stable without leaving two competing assistant schemas.
-- =============================================================================
