-- =============================================================================
-- 0028_foundation_payout.sql  [PLACEHOLDER]
-- foundation_990pf_data is fully defined in 0013_tax_contributions.sql,
-- which holds the canonical org-scoped schema, RLS policies, and grants.
-- This file is intentionally empty so the migration runner skips it cleanly.
-- =============================================================================
