-- =============================================================================
-- 0039_alignment_fixes.sql
-- Historical placeholder.
--
-- Receipt fields now live in 0014_donors.sql, and org_has_module aliases live
-- in 0001_extensions_and_shared_infra.sql. This migration intentionally creates
-- no objects so the migration numbering remains stable.
-- =============================================================================
