// lib/builder/github-apply.ts

export interface GitHubFile {
  path: string;
  content: string;
}

export interface ApplyResult {
  prUrl: string;
  branchName: string;
}

export function isGitHubConfigured(): boolean {
  return !!(
    process.env.GITHUB_TOKEN &&
    process.env.GITHUB_REPO_OWNER &&
    process.env.GITHUB_REPO_NAME
  );
}

export async function applyProposalToGitHub(
  proposalId: string,
  moduleName: string,
  files: GitHubFile[],
  reviewScore: number,
): Promise<ApplyResult> {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_REPO_OWNER;
  const repo  = process.env.GITHUB_REPO_NAME;

  if (!token || !owner || !repo) {
    throw new Error('GitHub integration not configured');
  }

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
  const base = `https://api.github.com/repos/${owner}/${repo}`;

  // 1. Get main branch SHA
  const refRes = await fetch(`${base}/git/ref/heads/main`, { headers });
  if (!refRes.ok) {
    throw new Error(`Failed to read main branch: ${refRes.status}`);
  }
  const refData = await refRes.json() as { object: { sha: string } };
  const mainSha = refData.object.sha;

  // 2. Create branch
  const branchName = `builder/scaffold-${proposalId.slice(0, 8)}`;
  const createBranchRes = await fetch(`${base}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: mainSha }),
  });
  if (!createBranchRes.ok) {
    throw new Error(`Failed to create branch: ${createBranchRes.status}`);
  }

  // 3. Write each file (GET existing SHA first — required for updates)
  for (const file of files) {
    const cleanPath = file.path.replace(/^\//, '');
    const contentB64 = Buffer.from(file.content, 'utf-8').toString('base64');

    // Check for existing file to get its SHA
    const existingRes = await fetch(
      `${base}/contents/${cleanPath}?ref=${branchName}`,
      { headers }
    );
    let existingSha: string | undefined;
    if (existingRes.ok) {
      const existingData = await existingRes.json() as { type?: string; sha?: string };
      if (existingData.type === 'file') {
        existingSha = existingData.sha;
      }
    } else if (existingRes.status !== 404) {
      throw new Error(`Failed to check ${cleanPath}: ${existingRes.status}`);
    }

    const body: Record<string, unknown> = {
      message: `feat(builder): add ${cleanPath}`,
      content: contentB64,
      branch: branchName,
    };
    if (existingSha) body.sha = existingSha;

    const putRes = await fetch(`${base}/contents/${cleanPath}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify(body),
    });
    if (!putRes.ok) {
      const errData = await putRes.json().catch(() => ({})) as Record<string, unknown>;
      throw new Error(
        `Failed to write ${cleanPath}: ${putRes.status} — ${errData.message ?? JSON.stringify(errData)}`
      );
    }
  }

  // 4. Open PR
  const prBody = [
    `## AI-Generated Module: ${moduleName}`,
    '',
    `**Review Score:** ${reviewScore}/100`,
    '',
    '**Files changed:**',
    files.map(f => `- \`${f.path}\``).join('\n'),
    '',
    '> This PR was generated by the Builder AI. Review all code carefully before merging.',
    '',
    `Proposal ID: \`${proposalId}\``,
  ].join('\n');

  const prRes = await fetch(`${base}/pulls`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      title: `feat(builder): scaffold ${moduleName}`,
      body: prBody,
      head: branchName,
      base: 'main',
    }),
  });
  if (!prRes.ok) {
    const errData = await prRes.json().catch(() => ({})) as Record<string, unknown>;
    throw new Error(
      `Failed to create PR: ${prRes.status} — ${errData.message ?? JSON.stringify(errData)}`
    );
  }
  const prData = await prRes.json() as { html_url: string };

  return { prUrl: prData.html_url, branchName };
}
