import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient, createServerClient } from '@/lib/supabase';
import { runAutomationRulesForEvent } from '@/lib/tasks/automation/dynamic-rules';
import { getOrgAccess, hasOrgAccess } from '@/lib/org-access';

// Grant milestone reverse sync: when a task generated by grant_obligations
// is completed, mark the linked grant_milestone as completed too.
async function syncGrantMilestoneCompletion(
  orgId: string,
  taskId: string,
  taskMetadata: Record<string, unknown> | null
): Promise<void> {
  if (!taskMetadata || taskMetadata.producer !== 'grant_obligations') return;

  const adminDb = createAdminClient();

  const { data: links } = await adminDb
    .from('task_entity_links')
    .select('entity_id')
    .eq('org_id', orgId)
    .eq('task_id', taskId)
    .eq('entity_type', 'grant_milestone');

  if (!links || links.length === 0) return;

  const milestoneId = links[0].entity_id as string;
  const today = new Date().toISOString().slice(0, 10);
  const { data: milestone, error: milestoneError } = await adminDb
    .from('grant_milestones')
    .select('id, grants!inner(org_id)')
    .eq('id', milestoneId)
    .eq('grants.org_id', orgId)
    .maybeSingle();

  if (milestoneError) throw milestoneError;
  if (!milestone) throw new Error('Linked grant milestone was not found in this organization');

  // DB CHECK constraint: status='completed' requires completed_date IS NOT NULL
  const { error } = await adminDb
    .from('grant_milestones')
    .update({ status: 'completed', completed_date: today })
    .eq('id', milestoneId);
  if (error) throw error;
}

export const dynamic = 'force-dynamic';

const NO_STORE = { 'Cache-Control': 'no-store' } as const;

interface RouteParams {
  params: Promise<{ orgId: string; taskId: string }>;
}

function json(body: unknown, init: ResponseInit = {}) {
  return NextResponse.json(body, {
    ...init,
    headers: {
      ...NO_STORE,
      ...(init.headers || {}),
    },
  });
}

export async function POST(_req: NextRequest, { params }: RouteParams) {
  try {
    const { orgId, taskId } = await params;
    const supabase = await createServerClient();
    const access = await getOrgAccess(supabase, orgId);
    if (!access.user) return json({ error: 'Unauthorized' }, { status: 401 });
    if (!hasOrgAccess(access, 'member')) return json({ error: 'Member access required' }, { status: 403 });
    const { user } = access;

    const adminClient = createAdminClient();
    const { data: existing } = await adminClient
      .from('tasks')
      .select('*')
      .eq('id', taskId)
      .eq('org_id', orgId)
      .is('deleted_at', null)
      .maybeSingle();

    if (!existing) return json({ error: 'Task not found' }, { status: 404 });
    if (!hasOrgAccess(access, 'admin') && existing.assigned_to !== user.id) {
      return json({ error: 'Not authorized to complete this task' }, { status: 403 });
    }

    if (existing.status === 'completed') {
      return json({ task: existing, idempotent: true });
    }

    const { data: task, error } = await adminClient
      .from('tasks')
      .update({
        status: 'completed',
        completed_at: new Date().toISOString(),
        completed_by: user.id,
      })
      .eq('id', taskId)
      .eq('org_id', orgId)
      .select()
      .single();

    if (error) return json({ error: error.message }, { status: 500 });

    try {
      await syncGrantMilestoneCompletion(
        orgId,
        taskId,
        (task?.metadata as Record<string, unknown> | null) ?? null
      );
    } catch (syncError: any) {
      await adminClient
        .from('tasks')
        .update({
          status: existing.status,
          completed_at: existing.completed_at,
          completed_by: existing.completed_by,
        })
        .eq('id', taskId)
        .eq('org_id', orgId);
      return json({ error: syncError.message }, { status: 500 });
    }

    const { error: eventError } = await adminClient.from('task_events').insert({
      task_id: taskId,
      org_id: orgId,
      actor_id: user.id,
      event_type: 'completed',
      before_values: existing,
      after_values: task,
    });
    if (eventError) {
      await adminClient
        .from('tasks')
        .update({
          status: existing.status,
          completed_at: existing.completed_at,
          completed_by: existing.completed_by,
        })
        .eq('id', taskId)
        .eq('org_id', orgId);
      return json({ error: eventError.message }, { status: 500 });
    }

    try {
      await runAutomationRulesForEvent(adminClient, {
        orgId,
        triggerType: 'task_completed',
        entityType: 'task',
        entityId: taskId,
        payload: {
          task_type: task.task_type,
          assigned_to: task.assigned_to,
          actor_id: user.id,
        },
      });
    } catch (automationErr) {
      console.error('Task completion automation failed:', automationErr);
    }

    return json({ task });
  } catch (err: any) {
    return json({ error: err.message }, { status: 500 });
  }
}
